/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CASS.ui;

import CASS.data.address.CompositeAddress;
import CASS.data.person.PersonDTO;
import CASS.manager.AddressManager;
import CASS.manager.PersonManager;
import CASS.services.ServiceError;
import CASS.util.DataObjectGenerator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

/**
 *
 * @author ctydi
 */
public class AddressView extends javax.swing.JPanel {

    private AddressManager manager;

    private GUIRunner caller;

    private List<CompositeAddress> addresses;

    /**
     * Creates new form AddressView
     */
    public AddressView(GUIRunner caller, AddressManager mng, PersonManager per) throws ServiceError {
        initComponents();
        this.manager = mng;
        this.caller = caller;
        this.loadData();

    }

    public GUIRunner getCaller() {
        return this.caller;
    }

    public AddressManager getManager() {
        return this.manager;
    }

    private void loadData() throws ServiceError {
        this.addresses = this.getManager().getFullAddress();
        this.setData(this.addresses);
    }

    private void setData(List<CompositeAddress> toSet) {
        Object[] data = new Object[toSet.size()];
        for (int index = 0; index < data.length; index++) {
            data[index] = toSet.get(index);
        }
        TableModel toUse = new AddressTableModel(data);
        this.addressTable.setModel(toUse);
    }

    private void filter() {

        List<CompositeAddress> toUse = DataObjectGenerator.createList();

        String street = this.stateFilter.getText().trim().toUpperCase();
        String town = this.townFilter.getText().trim().toUpperCase();
        String zip = this.zipFilter.getText().trim().toUpperCase();
        String state = this.stateFilter.getText().trim().toUpperCase();
        String country = this.countryFilter.getText().trim().toUpperCase();
        if (street.length() < 1) {
            if (town.length() < 1) {
                if (zip.length() < 1) {
                    if (state.length() < 1) {
                        if (country.length() < 1) {
                            this.setData(this.addresses);
                            return;
                        }
                    }
                }
            }
        }

        for (CompositeAddress addr : this.addresses) {
            boolean add = true;
            if (add == true) {
                if (street.length() > 0) {
                    if (!addr.getAddress().getStreet().toUpperCase().contains(street)) {

                        if (!addr.getAddress().getStreet2().toUpperCase().contains(street)) {
                            add = false;
                        }
                    }
                }
            }
            if (add == true) {
                if (town.length() > 0) {
                    if (!addr.getCity().getCityName().toUpperCase().contains(town)) {
                        add = false;
                    }
                }
            }
            if (add == true) {
                if (zip.length() > 0) {
                    if (!addr.getAddress().getPostCode().toUpperCase().contains(zip)) {
                        add = false;
                    }
                }
            }
            if (add == true) {
                if (state.length() > 0) {
                    if (!addr.getState().getAbbreviation().toUpperCase().contains(state)) {
                        if (!addr.getState().getStateName().toUpperCase().contains(state)) {
                            add = false;
                        }
                    }
                }
            }
            if (add == true) {
                if (country.length() > 0) {

                    if (!addr.getCountry().getCountryName().toUpperCase().contains(country)) {
                        if (!addr.getCountry().getCountryName().toUpperCase().contains(country)) {
                            add = false;
                        }
                    }
                }
            }

            if (add == true) {
                toUse.add(addr);
            }
        }
        this.setData(toUse);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        countryFilter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        stateFilter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        townFilter = new javax.swing.JTextField();
        Town = new javax.swing.JLabel();
        zipFilter = new javax.swing.JTextField();
        zipLabel = new javax.swing.JLabel();
        streetFilter = new javax.swing.JTextField();
        zipLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        zipDisplay = new javax.swing.JTextField();
        townDisplay = new javax.swing.JTextField();
        counrtyDisplay = new javax.swing.JTextField();
        stateDisplay = new javax.swing.JTextField();
        streetDisplay = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();

        countryFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                countryFilterKeyReleased(evt);
            }
        });

        jLabel1.setText("Country");

        stateFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stateFilterKeyReleased(evt);
            }
        });

        jLabel2.setText("State");

        townFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                townFilterKeyReleased(evt);
            }
        });

        Town.setText("Town");

        zipFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zipFilterKeyReleased(evt);
            }
        });

        zipLabel.setText("Zip");

        streetFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                streetFilterKeyReleased(evt);
            }
        });

        zipLabel1.setText("Steet");

        addressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        addressTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        addressTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(addressTable);

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        zipDisplay.setEditable(false);

        townDisplay.setEditable(false);

        counrtyDisplay.setEditable(false);

        stateDisplay.setEditable(false);

        streetDisplay.setEditable(false);

        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(personTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(1059, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(zipFilter)
                            .addComponent(townFilter)
                            .addComponent(stateFilter)
                            .addComponent(zipLabel1)
                            .addComponent(zipLabel)
                            .addComponent(Town)
                            .addComponent(jLabel2)
                            .addComponent(countryFilter)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(streetFilter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stateDisplay)
                            .addComponent(counrtyDisplay, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(streetDisplay)
                            .addComponent(zipDisplay, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(townDisplay, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(countryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(1, 1, 1)
                                .addComponent(stateFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Town)
                                .addGap(1, 1, 1)
                                .addComponent(townFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zipLabel)
                                .addGap(1, 1, 1)
                                .addComponent(zipFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zipLabel1)
                                .addGap(1, 1, 1)
                                .addComponent(streetFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(counrtyDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stateDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(townDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zipDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(streetDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void countryFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countryFilterKeyReleased
        filter();

    }//GEN-LAST:event_countryFilterKeyReleased

    private void stateFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stateFilterKeyReleased
        filter();
    }//GEN-LAST:event_stateFilterKeyReleased

    private void townFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_townFilterKeyReleased
        filter();

    }//GEN-LAST:event_townFilterKeyReleased

    private void zipFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zipFilterKeyReleased
        filter();
    }//GEN-LAST:event_zipFilterKeyReleased

    private void streetFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_streetFilterKeyReleased
        filter();
    }//GEN-LAST:event_streetFilterKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.countryFilter.setText("");
        this.stateFilter.setText("");
        this.townFilter.setText("");
        this.zipFilter.setText("");
        this.streetFilter.setText("");
        this.filter();
        this.setAddress(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void setAddress(int key) {
        this.streetDisplay.setText("");
        this.zipDisplay.setText("");
        this.townDisplay.setText("");
        this.stateDisplay.setText("");
        this.counrtyDisplay.setText("");
        if (key < 0) {
            return;
        }
        for (CompositeAddress adr : this.addresses) {
            if (adr.getAddress().getKey() == key) {
                this.streetDisplay.setText(adr.getAddress().getStreet() + " " + adr.getAddress().getStreet2());
                this.zipDisplay.setText((adr.getAddress().getPostCode()));
                this.townDisplay.setText(adr.getCity().getCityName());
                this.stateDisplay.setText(adr.getState().getStateName());
                this.counrtyDisplay.setText(adr.getCountry().getCountryName());
                return;
            }

        }
    }

    private void addressTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressTableMouseClicked
        int row = this.addressTable.getSelectedRow();
        AddressTableModel model = (AddressTableModel) this.addressTable.getModel();
        int key = (int) model.getValueAt(row, -1);
        setAddress(key);

        try {
            List<PersonDTO> people = this.getCaller().getPersonManager().getPeopleByAddress(key);
            PersonTableModel peopleModel = new PersonTableModel(people.toArray(), true);
            this.personTable.setModel(peopleModel);

        } catch (ServiceError ex) {
            this.getCaller().displayError(ex);
        }

    }//GEN-LAST:event_addressTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Town;
    private javax.swing.JTable addressTable;
    private javax.swing.JTextField counrtyDisplay;
    private javax.swing.JTextField countryFilter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable personTable;
    private javax.swing.JTextField stateDisplay;
    private javax.swing.JTextField stateFilter;
    private javax.swing.JTextField streetDisplay;
    private javax.swing.JTextField streetFilter;
    private javax.swing.JTextField townDisplay;
    private javax.swing.JTextField townFilter;
    private javax.swing.JTextField zipDisplay;
    private javax.swing.JTextField zipFilter;
    private javax.swing.JLabel zipLabel;
    private javax.swing.JLabel zipLabel1;
    // End of variables declaration//GEN-END:variables
}
