/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jterminal.ui;

import java.awt.Canvas;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import java.awt.LayoutManager;
import java.awt.event.KeyEvent;
import java.util.List;
import jterminal.manager.BaseCommander;
import jterminal.manager.Commandable;
import jterminal.manager.JTerminalManager;
import jterminal.sql.SqlCommander;

/**
 *
 * @author ctydi
 */
public class TerminalPanel extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form NewJPanel
     */
    int width;

    int height;

    private long last;

    boolean shift = false;
    JTerminalManager manager;

    Commandable commander;

    public TerminalPanel() {
        initComponents();
        this.width = 100;
        this.height = 100;
        this.setFocusable(true);
        this.updateManager();
        this.commander = new SqlCommander(this.manager);

    }

    private void updateManager() {
        if (this.getManager() == null) {
            this.manager = new JTerminalManager(250, this.getRowCount(), this.getColCount());
        } else {
            this.getManager().updateDimensions(this.getRowCount(), this.getColCount());
        }

    }

    private int getColCount() {
        double value = (this.width - this.getPadding() * 2) / 8;
        return (int) (value);
    }

    private int getRowCount() {
        double ret = (this.height - this.getPadding() * 5) / this.rowHeight();

        return (int) (ret);
    }

    private JTerminalManager getManager() {
        return this.manager;
    }

    @Override
    public void paint(Graphics g) {

        super.paint(g);
        this.fillDisplay(g);
        this.setupForText(g);
        this.printInput(g);
        this.printOutput(g);

    }

    private void printOutput(Graphics g) {
        List<String> out = this.getCommander().getOutput();
        int row = 0;

        for (String line : out) {
            this.printLine(g, line, row);

            row++;
        }

    }

    public void setDimensions(int width, int height) {
        this.setSize(width, height);

        // this.display.setBounds(0, 0, width, height);
        //this.display.setLocation(0, 0);
    }

    private double rowHeight() {
        return 16;
    }

    private Commandable getCommander() {
        return this.commander;
    }

    private void printInput(Graphics g) {
        long curr = System.currentTimeMillis();

        int row = this.getManager().getHeight() + 1;
        long check = System.currentTimeMillis() % 1000;

        boolean cursor = check > 500;

        long diff = curr - this.last;

        if (diff < 1000) {
            cursor = true;
        }

        String line = this.getManager().getFormattedInput(cursor);

        this.printLine(g, line, row);

    }

    private void fillDisplay(Graphics g) {
        Color toSet = new Color(26, 26, 26);
        g.setColor(toSet);
        g.clearRect(0, 0, width, height);
        int width = this.getWidth();
        int height = this.getHeight();

        g.fillRect(0, 0, width, height);

    }

    public int getWidth() {
        return this.width;

    }

    public int getHeight() {
        return this.height;
    }

    private int getPrintHeight(int row) {
        double ret = this.getPadding() * 5;
        ret += row * this.rowHeight() - this.rowHeight();
        return (int) ret;
    }

    private void setupForText(Graphics g) {
        Color toUse = new Color(0, 128, 43);
        g.setColor(toUse);
        Font curr = this.getFont();

        g.setFont(this.getTerminalFont());

    }

    private int getTextOffset() {
        return 10;
    }

    private void printLine(Graphics g, String line, int row) {

        int y = this.getPrintHeight(row);
        g.drawString(line, this.getTextOffset() * 2, y);

    }

    private Font getTerminalFont() {

        //  GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        //   String[] fonts = ge.getAvailableFontFamilyNames();
        return new Font("Monospaced", Font.BOLD, 12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void processKeyDown(KeyEvent evt) {
        this.last = System.currentTimeMillis();
        if (skipChar(evt) == true) {
            return;
        }

        boolean add = true;
        if (evt.getKeyCode() == 8) {
            add = false;
            this.getManager().trimInput();
        }

        if (evt.getKeyCode() == 16) {
            add = false;

        }

        if (evt.getKeyCode() == 17) {
            add = false;

        }

        if (evt.getKeyCode() == 10) {
            add = false;
            this.processInput();
        }

        if (evt.getKeyCode() == 37) {
            add = false;
            this.getManager().decrementInputCursor();

        }

        if (evt.getKeyCode() == 39) {
            add = false;
            this.getManager().incrementInputCursor();

        }

        if (evt.getKeyCode() == 38) {
            add = false;

            this.getManager().incrementIndex(evt.isShiftDown());

        }

        if (evt.getKeyCode() == 40) {
            add = false;
            this.getManager().decrementIndex(evt.isShiftDown());

        }

        if (add == true) {
            this.getManager().appendInput(evt.getKeyChar() + "");
        }
        // this.display.repaint();
        this.repaint();
    }

    private boolean skipChar(KeyEvent evt) {
        if (evt.getKeyChar() == KeyEvent.SHIFT_DOWN_MASK) {
            return true;
        }

        if (evt.getKeyCode() == 20) {
            return true;
        }

        return false;
    }

    private void processInput() {
        String input = this.getManager().getInput();
        this.getCommander().processInput(input);
    }

    private void clear() {
        this.getManager().clearOutput();
        this.repaint();
    }

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

    }//GEN-LAST:event_formKeyReleased

    private int getPadding() {
        return 10;
    }

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        this.width = evt.getComponent().getParent().getWidth() - this.getPadding() * 2;
        this.height = evt.getComponent().getParent().getHeight() - this.getPadding() * 2;

        this.updateManager();
        this.repaint();
    }//GEN-LAST:event_formComponentResized

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        processKeyDown(evt);
    }//GEN-LAST:event_formKeyPressed

    // public Canvas getDisplay() {
    //    return this.display;
    //  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void run() {

        while (true) {
            this.repaint();
        }
    }
}
