/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cass;

import cass.data.address.AddressSearchParameters;
import cass.data.address.CitySearchParameters;
import cass.data.address.CountryDTO;
import cass.data.address.CountrySearchParameters;
import cass.data.address.StateSearchParameters;
import cass.services.AddressService;
import cass.services.ServiceError;
import cass.services.mysql.AddressSearchBuilder;
import cass.services.mysql.MySqlService;
import cass.services.mysql.SqlAddressService;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

public class App {

    private String test;

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws SQLException, ServiceError {
        /*   CountrySearchParameters con = new CountrySearchParameters();

        con.addCountryAbbv("USA");

        StateSearchParameters state = new StateSearchParameters();

        //   state.addStateName("ALASKA");
        state.addCountry(con);
        CitySearchParameters city = new CitySearchParameters();

        city.addCityName("ANCHOR");

        city.setParameterIsExact(CitySearchParameters.CITY_NAME, false);
        city.addState(state);

        AddressSearchParameters adr = new AddressSearchParameters();
        adr.setCity(city);

        System.out.println(AddressSearchBuilder.createQueryForAddress(adr));
         */

        MySqlService mysql = new MySqlService("root", "Per@grin1", "localhost", "3306", "DA19785");

        AddressService adrSvc = new SqlAddressService(mysql);

        CountryDTO toCreate = new CountryDTO("UNITED KINGDOM", "UK");
        int id = adrSvc.addCountry(toCreate);
        toCreate = new CountryDTO("UNITED STATES", "USA");
        toCreate = new CountryDTO("UNITED STATES", "USA");
        id = adrSvc.addCountry(toCreate);

        //  System.out.println(id);
    }
}
