/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CASS;

import CASS.data.address.AddressSearchParameters;
import CASS.data.address.CitySearchParameters;
import CASS.data.address.CountryDTO;
import CASS.data.address.CountrySearchParameters;
import CASS.data.address.StateSearchParameters;
import CASS.services.AddressService;
import CASS.services.ServiceError;
import CASS.services.mysql.AddressSearchBuilder;
import CASS.services.mysql.MySqlService;
import CASS.services.mysql.SqlAddressService;
import java.sql.ResultSet;
import java.sql.SQLException;


public class App {

    private String test;

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws SQLException, ServiceError {
        /*   CountrySearchParameters con = new CountrySearchParameters();

        con.addCountryAbbv("USA");

        StateSearchParameters state = new StateSearchParameters();

        //   state.addStateName("ALASKA");
        state.addCountry(con);
*/
        CitySearchParameters city = new CitySearchParameters(1);

      //  city.addCityName("ANCHOR");

       //city.setParameterIsExact(CitySearchParameters.CITY_NAME, false);
      //  city.addState(state);

        AddressSearchParameters adr = new AddressSearchParameters();
        adr.setCity(city);
        
          System.out.println(AddressSearchBuilder.createQueryForCity(city));
        
        

      //  System.out.println(AddressSearchBuilder.createQueryForAddress(adr));
        

       /* MySqlService mysql = new MySqlService("root", "Per@grin1", "localhost", "3306", "DA19785");

        AddressService adrSvc = new SqlAddressService(mysql);

        CountryDTO toCreate = new CountryDTO("UNITED KINGDOM", "UK");
        int id = adrSvc.addCountry(toCreate);
        toCreate = new CountryDTO("UNITED STATES", "USA");
        id = adrSvc.addCountry(toCreate);
*/
        //  System.out.println(id);
    }
}
